### ISSUE TITLE
LSST survey broken?

### ISSUE THREAD

**Issue by musoke** [deepskies/deeplenstronomy#53]
The LSST survey seems to be broken in version 0.0.1.3

Steps to reproduce:

- open [Surveys.ipynb example notebook](https://github.com/deepskies/deeplenstronomy/blob/master/Notebooks/Surveys.ipynb)

- change cell 5 to 
```
dataset = dl.make_dataset('data/demo.yaml', survey='lsst', store_in_memory=False, store_sample=True, verbose=True)
```

This results in an error, 

```
SURVEY.PARAMETERS.num_exposures.DISTRIBUTION.PARAMETERS must be a dictionary or None

Fatal error(s) detected in config file. Please edit and rerun.

---------------------------------------------------------------------------
ConfigFileError                           Traceback (most recent call last)
~/anaconda3/envs/deeplens/lib/python3.7/site-packages/deeplenstronomy/check.py in _run_checks(full_dict, config_dict)
    959     try:
--> 960         check_runner = AllChecks(full_dict, config_dict)
    961     except ConfigFileError:

~/anaconda3/envs/deeplens/lib/python3.7/site-packages/deeplenstronomy/check.py in __init__(self, full_dict, config_dict)
     83             _kind_output(total_errs)
---> 84             raise ConfigFileError
     85 

ConfigFileError: 

During handling of the above exception, another exception occurred:

ConfigFileError                           Traceback (most recent call last)
<ipython-input-6-2a8fd3d7f5db> in <module>
----> 1 dataset = dl.make_dataset('data/demo.yaml', survey='lsst', store_in_memory=False, store_sample=True, verbose=True)

~/anaconda3/envs/deeplens/lib/python3.7/site-packages/deeplenstronomy/deeplenstronomy.py in make_dataset(config, dataset, save_to_disk, store_in_memory, verbose, store_sample, image_file_format, survey, return_planes, skip_image_generation, solve_lens_equation)
    313         if not _check_survey(survey):
    314             raise RuntimeError("survey={0} is not a valid survey.".format(survey))
--> 315         parser = Parser(config, survey=survey)
    316         dataset.config_dict = parser.config_dict
    317 

~/anaconda3/envs/deeplens/lib/python3.7/site-packages/deeplenstronomy/input_reader.py in __init__(self, config, survey)
     49 
     50         # Check for user errors in inputs
---> 51         self.check()
     52 
     53         return

~/anaconda3/envs/deeplens/lib/python3.7/site-packages/deeplenstronomy/input_reader.py in check(self)
    173         Check configuration file for possible user errors.
    174         """
--> 175         big_check._run_checks(self.full_dict, self.config_dict)
    176 
    177         return

~/anaconda3/envs/deeplens/lib/python3.7/site-packages/deeplenstronomy/check.py in _run_checks(full_dict, config_dict)
    961     except ConfigFileError:
    962         print("\nFatal error(s) detected in config file. Please edit and rerun.")
--> 963         raise ConfigFileError
    964 
    965     return

ConfigFileError: 

```

**Comment by rmorgan10** [comment]
Hi Nathan, thanks for the heads up! I've seen this pop up and I believe it should be fixed in the newest version of deeplenstronomy (which I will release tomorrow). I'll verify that lsst survey mode doesn't cause an issue for that release.

**Comment by musoke** [comment]
That's great, thanks @rmorgan10!

**Comment by rmorgan10** [comment]
Hi @musoke,

To use Rubin Observatory / LSST quality simulations, for the time being you can use this for the IMAGE and SURVEY sections of your main configuration file:

```
IMAGE:
    PARAMETERS:
        exposure_time:
            DISTRIBUTION:
                NAME: lsst_exposure_time
                PARAMETERS: None
        numPix: 100
        pixel_scale: 0.2
        psf_type: 'GAUSSIAN'
        read_noise: 10
        ccd_gain: 2.3

SURVEY:
    PARAMETERS:
        BANDS: u,g,r,i,z,Y
        seeing:
            DISTRIBUTION:
                NAME: lsst_seeing
                PARAMETERS: None
        magnitude_zero_point:
            DISTRIBUTION:
                NAME: lsst_magnitude_zero_point
                PARAMETERS: None
        sky_brightness:
            DISTRIBUTION:
                NAME: lsst_sky_brightness
                PARAMETERS: None
        num_exposures:
            DISTRIBUTION:
                NAME: lsst_num_exposures
                PARAMETERS:
                    coadd_years: 10
```

This text in your configuration files will give you the same functionality of passing `survey='lsst'`. 

The issue was that the "coadd_years" parameter was missing from the lsst survey mode. So thanks for pointing it out! This was actually a different issue than I thought it was. Like I said above, I'll be releasing a new version today that will include this fix, but until then the text above should prevent you from waiting on the official release.
