### ISSUE TITLE
Odd artifacting issue with making Einstein rings. 

### ISSUE THREAD

**Issue by Jasonpoh** [deepskies/deeplenstronomy#67]
Creating a sample of toy DES-like Einstein rings using this configuration file:

```
DATASET:
    NAME: test 
    PARAMETERS:
        SIZE: 100 
        OUTDIR: test 
        SEED: 10

COSMOLOGY:
    PARAMETERS:
        H0: 70
        Om0: 0.3

IMAGE:
    PARAMETERS:
        exposure_time: 300
        numPix: 32
        pixel_scale: 0.263
        psf_type: 'GAUSSIAN'
        read_noise: 7
        ccd_gain: 6.083

SURVEY:
    PARAMETERS:
        BANDS: g
        seeing: 0.9
        magnitude_zero_point: 30.0
        sky_brightness: 30.0
        num_exposures: 10

SPECIES:
    GALAXY_1:
        NAME: LENS
        LIGHT_PROFILE_1:
            NAME: SERSIC_ELLIPSE
            PARAMETERS:
                magnitude: 100
                center_x: 0
                center_y: 0
                R_sersic: 1
                n_sersic: 4
                e1: 0 
                e2: 0 

        MASS_PROFILE_1:
            NAME: SIE
            PARAMETERS:
                theta_E:
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: 0.5
                            maximum: 4.0
                e1: 0
                e2: 0
                center_x: 0
                center_y: 0

    GALAXY_2:
        NAME: SOURCE
        LIGHT_PROFILE_1:
            NAME: SERSIC_ELLIPSE
            PARAMETERS:
                magnitude: 21
                center_x: 0.0
                center_y: 0.0
                R_sersic: 0.5
                n_sersic: 4
                e1: 0
                e2: 0

        MASS_PROFILE_1:
            NAME: SIE
            PARAMETERS:
                theta_E: 2.0
                e1: 0.1
                e2: -0.1
                center_x: 0.0
                center_y: 0.0

GEOMETRY:
    CONFIGURATION_1:
        NAME: GALAXY_AGN
        FRACTION: 1
        PLANE_1:
            OBJECT_1: LENS
            PARAMETERS:
                REDSHIFT: 0.5
        PLANE_2:
            OBJECT_1: SOURCE
            PARAMETERS:
                REDSHIFT: 2.0
```

produces Einstein rings with some artifacting, perhaps from pixelization? 

![image](https://user-images.githubusercontent.com/17857920/162533752-a5e0576a-158a-4353-80ed-640232297742.png)
