### ISSUE TITLE
LSST survey parameters

### ISSUE THREAD

**Issue by musoke** [deepskies/deeplenstronomy#75]
Currently the LSST survey parameters have 

```

IMAGE:
    PARAMETERS:
        exposure_time:
            DISTRIBUTION:
                NAME: lsst_exposure_time
                PARAMETERS: None
        numPix: 100
        pixel_scale: 0.2
        psf_type: 'GAUSSIAN'
        read_noise: 10
        ccd_gain: 2.3
SURVEY:
    PARAMETERS:
        BANDS: u,g,r,i,z,Y
        seeing:
            DISTRIBUTION:
                NAME: lsst_seeing
                PARAMETERS: None
        magnitude_zero_point:
            DISTRIBUTION:
                NAME: lsst_magnitude_zero_point
                PARAMETERS: None
        sky_brightness:
            DISTRIBUTION:
                NAME: lsst_sky_brightness
                PARAMETERS: None
        num_exposures:
            DISTRIBUTION:
                NAME: lsst_num_exposures
                PARAMETERS:
                    coadd_years: 10
```

These could be more realistic.  For example, `lsst_magnitude_zero_point`, `lsst_sky_brightness` and `lsst_seeing` should not be `None`.
